// utils/crypto.js
const crypto = require('crypto');

/**
 * Encrypt data using AES-256-CBC
 * @param {Object} data - Data to encrypt
 * @param {String} key - Encryption key
 * @returns {String} Encrypted data in hex format
 */
function encryptPayload(data, key) {
  try {
    const cipher = crypto.createCipher('aes-256-cbc', key);
    let encrypted = cipher.update(JSON.stringify(data), 'utf8', 'hex');
    encrypted += cipher.final('hex');
    return encrypted;
  } catch (error) {
    throw new Error('Encryption failed: ' + error.message);
  }
}

/**
 * Decrypt data using AES-256-CBC
 * @param {String} encrypted - Encrypted data in hex format
 * @param {String} key - Decryption key
 * @returns {Object} Decrypted data as object
 */
function decryptPayload(encrypted, key) {
  try {
    const decipher = crypto.createDecipher('aes-256-cbc', key);
    let decrypted = decipher.update(encrypted, 'hex', 'utf8');
    decrypted += decipher.final('utf8');
    return JSON.parse(decrypted);
  } catch (error) {
    throw new Error('Decryption failed: ' + error.message);
  }
}

/**
 * Create HMAC-SHA256 signature for payload
 * @param {Object} data - Data to sign
 * @param {String} key - Secret key
 * @returns {String} Signature in hex format
 */
function signPayload(data, key) {
  const hmac = crypto.createHmac('sha256', key);
  hmac.update(JSON.stringify(data));
  return hmac.digest('hex');
}

/**
 * Verify payload signature
 * @param {Object} data - Data to verify
 * @param {String} signature - Signature to verify against
 * @param {String} key - Secret key
 * @returns {Boolean} True if signature is valid
 */
function verifySignature(data, signature, key) {
  const expectedSignature = signPayload(data, key);
  return expectedSignature === signature;
}

/**
 * Generate random packet ID
 * @returns {String} Random packet ID
 */
function generatePacketId() {
  return crypto.randomBytes(16).toString('hex');
}

/**
 * Generate transaction ID
 * @returns {String} Random transaction ID
 */
function generateTransactionId() {
  return crypto.randomBytes(12).toString('hex');
}

/**
 * Generate nonce for payment
 * @returns {String} Random nonce
 */
function generateNonce() {
  return crypto.randomBytes(16).toString('hex');
}

module.exports = {
  encryptPayload,
  decryptPayload,
  signPayload,
  verifySignature,
  generatePacketId,
  generateTransactionId,
  generateNonce
};

/*
CRYPTOGRAPHY EXPLANATION:

1. ENCRYPTION (AES-256-CBC)
   - Data encrypted with device key
   - Only bridge node can decrypt (has the key)
   - Intermediate nodes cannot read the data
   - Flow: Plain text → AES-256 → Encrypted hex string

2. SIGNATURE (HMAC-SHA256)
   - Verifies data hasn't been tampered with
   - Generated by sender, verified by backend
   - Using device key as secret
   - Flow: Data + Key → HMAC → Signature

3. PACKET ID
   - Unique identifier for each payment
   - Prevents double-settling same payment
   - Generated randomly using crypto

4. NONCE
   - Random value in each payment
   - Prevents replay attacks
   - Changes every payment even if amount/recipient same

SECURITY FLOW:
1. Sender creates payment locally
2. Sender encrypts with device key
3. Sender signs with HMAC
4. Packet sent through mesh (encrypted, can't be read)
5. Bridge node uploads to backend
6. Backend decrypts with device key
7. Backend verifies signature
8. Backend checks funds
9. Backend settles payment
10. Backend marks packet as settled (prevents double-settle)
*/
